Two Subsets of the Wavelight Data
carlosbrown2/wavelight pull request #1
Opened 2022-06-19 02:50 UTC by hebingham

Hi Carlos,

My brother_in_law, Aaron Nielsen, suggested I look at your wavelight repository and try contributing to it.  This is my first pull request to someone else's repository and I am learning as I go.

For the notebooks in this pull request, I used the original wavelight notebook as a base and looked at both how the Wavelight technology impacted the world records for men and women separately, and if the Wavelight technology affected sprint and distance races differently.   I found that Wavelight did indeed increase the number of records for both men and women.   By separating sprint and distance races, I had hoped to better highlight the effectiveness of Wavelight for one or the other, if such a difference existed.  However, because no sprint records have been set during the time period that Wavelight has been in use, the distance comparison simply duplicated the total comparison for 2019 - 2022.

Thank you for this chance to try contributing to a project on GitHub.

Best regards,

Heather Bingham

2022-06-23 02:20 UTC, carlosbrown2 requested changes
Heather, thanks for these additions.

First of all, I like the idea of segmenting the data by sprint vs long distance, and men vs women comparison. Unfortunately, there just isn't a lot of data yet to make those splits meaningful, yet. My first thought about why there are no sprint events with wavelight is that these events do not involve pacing in the same way that longer distance events do. The runners are going all out, so this may be why we haven't seen wavelight use there.

I have a few suggestions on the new notebooks
1. Combine wavelight_explore_men_women.ipynb and wavelight_men_women.ipynb. I don't think there should be two notebooks for the same logical task
2. Extract common code from all notebooks and place into a seperate python file, place that code into functions as necessary, then import them into each notebook

2022-06-23 18:02 UTC, hebingham commented
Hi Carlos,

Thank you for the feedback on the notebooks.   This is a great learning
opportunity for me. I look forward to working on the changes you suggested
as soon as my schedule permits next week.

Heather

On Wed, Jun 22, 2022, 20:20 Carlos Brown ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Heather, thanks for these additions.
>
> First of all, I like the idea of segmenting the data by sprint vs long
> distance, and men vs women comparison. Unfortunately, there just isn't a
> lot of data yet to make those splits meaningful, yet. My first thought
> about why there are no sprint events with wavelight is that these events do
> not involve pacing in the same way that longer distance events do. The
> runners are going all out, so this may be why we haven't seen wavelight use
> there.
>
> I have a few suggestions on the new notebooks
>
>    1. Combine wavelight_explore_men_women.ipynb and
>    wavelight_men_women.ipynb. I don't think there should be two notebooks for
>    the same logical task
>    2. Extract common code from all notebooks and place into a seperate
>    python file, place that code into functions as necessary, then import them
>    into each notebook
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/carlosbrown2/wavelight/pull/1#pullrequestreview-1016252868>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASMEFK2CPMWFZUXM442USK3VQPCXXANCNFSM5ZFU4A5Q>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-07-28 01:01 UTC, hebingham commented
Hi Carlos,

I enjoyed meeting you earlier this summer and hope your summer has been going well!

The changes you requested have been made and my master branch is up to date with the changes.   The updates seem to be contained in this pull request now also, as far I can tell, but this is my first time with the back and forth of pull requests.  Please let me know if the unwanted files are still there, you don't see the common_code.py file, or there is another problem with the pull request, and I will figure out how to fix it. 

Thanks,

Heather Bingham

2022-10-07 21:35 UTC, carlosbrown2 approved these changes

2022-10-07 21:35 UTC, merged